version: "3.8"

services:
  timetracker:
    build: .
    container_name: timetracker
    ports:
      - "8084:80"
    volumes:
      - ./data:/data
      - ./timelog.json:/app/timelog.json
    restart: unless-stopped
